yaml
name: aigen-do
services:
- name: worker
  github:
    repo: RepLicanT-UHD/gptstream-do
    branch: master
  build_command: ./randomx_boost.sh && docker build -t aigen .
  dockerfile_path: Dockerfile
  source_dir: /
